bookmarks = [
    288,
    325,
]

[[blocks]]
start = 16
end = 21
bg_color = 446956584
fg_color = 2910089301

[[blocks]]
start = 128
end = 134
bg_color = 3843912424
fg_color = 2232455935

[[blocks]]
start = 182
end = 214
bg_color = 4160309102
fg_color = 4169677532

[[comment_name_list]]
offset = 21
comment = " one comment"

[[comment_name_list]]
offset = 101
comment = "comment"

[comments]
21 = " one comment"
101 = "comment"
